name: test workflow

on:
  push:
    branches:
      - test

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_NAME: "my-cool-app"

jobs:
  lint:
    name: list
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.export.outputs.status }}

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: run command
        id: export
        run:
          echo "Status=Complete" >> "$GITHUB_OUTPUT"
  
  test:
    name: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: lint
    steps:
      - name: run command
        run:
          echo "Doing thee test...${{ needs.lint.outputs.status}}"
